// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tm/tagmsg.proto

/*
Package tm is a generated protocol buffer package.

Put Service

Put Service API consists of a single service which returns a message.

It is generated from these files:
	tm/tagmsg.proto

It has these top-level messages:
	PutRequest
	PutResponse
*/
package tm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Message represents a simple message sent to the Put service.
type PutRequest struct {
	// Client IP represents the message identifier.
	ClientIp string `protobuf:"bytes,1,opt,name=client_ip,json=clientIp" json:"client_ip,omitempty"`
	// Server IP represents the message identifier.
	ServerIp string `protobuf:"bytes,2,opt,name=server_ip,json=serverIp" json:"server_ip,omitempty"`
	// Tags.
	Tags map[string]string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The message to be saved.
	Message string `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PutRequest) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *PutRequest) GetServerIp() string {
	if m != nil {
		return m.ServerIp
	}
	return ""
}

func (m *PutRequest) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *PutRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PutResponse struct {
	// The response message.
	ResponseMsg string `protobuf:"bytes,1,opt,name=response_msg,json=responseMsg" json:"response_msg,omitempty"`
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PutResponse) GetResponseMsg() string {
	if m != nil {
		return m.ResponseMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*PutRequest)(nil), "tagmsg.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "tagmsg.PutResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PutService service

type PutServiceClient interface {
	// Put method receives a simple message and returns it.
	// The message posted as the id parameter will also be returned.
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
}

type putServiceClient struct {
	cc *grpc.ClientConn
}

func NewPutServiceClient(cc *grpc.ClientConn) PutServiceClient {
	return &putServiceClient{cc}
}

func (c *putServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := grpc.Invoke(ctx, "/tagmsg.PutService/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PutService service

type PutServiceServer interface {
	// Put method receives a simple message and returns it.
	// The message posted as the id parameter will also be returned.
	Put(context.Context, *PutRequest) (*PutResponse, error)
}

func RegisterPutServiceServer(s *grpc.Server, srv PutServiceServer) {
	s.RegisterService(&_PutService_serviceDesc, srv)
}

func _PutService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PutServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tagmsg.PutService/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PutServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PutService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tagmsg.PutService",
	HandlerType: (*PutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _PutService_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tm/tagmsg.proto",
}

func init() { proto.RegisterFile("tm/tagmsg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x3d, 0x4f, 0xf3, 0x40,
	0x10, 0x84, 0x5f, 0x7f, 0xbc, 0x01, 0xaf, 0x91, 0x40, 0x0b, 0x85, 0x15, 0x28, 0x82, 0xab, 0x54,
	0xc6, 0x0a, 0x05, 0x88, 0x82, 0x02, 0x89, 0x22, 0x05, 0x52, 0x64, 0xa8, 0x68, 0x22, 0x13, 0xad,
	0x4e, 0x16, 0xf1, 0x07, 0xb7, 0x6b, 0x4b, 0xf9, 0x8d, 0xfc, 0x29, 0xe4, 0xbb, 0x0b, 0x08, 0xd1,
	0xed, 0xcc, 0xac, 0x9e, 0x9d, 0x3b, 0x38, 0x96, 0xfa, 0x4a, 0x4a, 0x55, 0xb3, 0xca, 0x3a, 0xdd,
	0x4a, 0x8b, 0x13, 0xab, 0xd2, 0x4f, 0x0f, 0x60, 0xd5, 0x4b, 0x41, 0x1f, 0x3d, 0xb1, 0xe0, 0x39,
	0x44, 0x9b, 0x6d, 0x45, 0x8d, 0xac, 0xab, 0x2e, 0xf1, 0x66, 0xde, 0x3c, 0x2a, 0x0e, 0xad, 0xb1,
	0xec, 0xc6, 0x90, 0x49, 0x0f, 0xa4, 0xc7, 0xd0, 0xb7, 0xa1, 0x35, 0x96, 0x1d, 0xe6, 0x10, 0x4a,
	0xa9, 0x38, 0x09, 0x66, 0xc1, 0x3c, 0x5e, 0x5c, 0x64, 0xee, 0xda, 0x0f, 0x3b, 0x7b, 0x29, 0x15,
	0x3f, 0x36, 0xa2, 0x77, 0x85, 0xd9, 0xc4, 0x04, 0x0e, 0x6a, 0x62, 0x2e, 0x15, 0x25, 0xa1, 0x81,
	0xed, 0xe5, 0xf4, 0x06, 0xa2, 0xef, 0x65, 0x3c, 0x81, 0xe0, 0x9d, 0x76, 0xae, 0xcc, 0x38, 0xe2,
	0x19, 0xfc, 0x1f, 0xca, 0x6d, 0x4f, 0xae, 0x83, 0x15, 0x77, 0xfe, 0xad, 0x97, 0xe6, 0x10, 0x9b,
	0x83, 0xdc, 0xb5, 0x0d, 0x13, 0x5e, 0xc2, 0x91, 0x76, 0xf3, 0xba, 0x66, 0xe5, 0x18, 0xf1, 0xde,
	0x7b, 0x62, 0xb5, 0xb8, 0x37, 0xcf, 0x7f, 0x26, 0x3d, 0x54, 0x1b, 0xc2, 0x1c, 0x82, 0x55, 0x2f,
	0x88, 0x7f, 0xdb, 0x4f, 0x4f, 0x7f, 0x79, 0x16, 0x90, 0xfe, 0x7b, 0x08, 0x5f, 0x7d, 0xa9, 0xdf,
	0x26, 0xe6, 0x53, 0xaf, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xea, 0x83, 0xfb, 0xcf, 0x67, 0x01,
	0x00, 0x00,
}
